
apiVersion: v1
kind: ConfigMap
metadata:
  name: greeting-api-config
data:
  application.properties: |
    spring.application.name=greeting-api
    server.port=8080
    logging.level.root=INFO
    logging.level.com.example.greeting=DEBUG
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    management.endpoint.health.show-details=always
    management.health.livenessState.enabled=true
    management.health.readinessState.enabled=true
