
apiVersion: v1
kind: Service
metadata:
  name: greeting-api-service
  labels:
    app: greeting-api
spec:
  type: LoadBalancer
  selector:
    app: greeting-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: ClientIP
